//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_inventory.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("ScbowOVmvJ8NRMPZdxIvTNn8Fz4tmB4A7BLD95jr/v3ka1i8k5IdvMqoByEwflNyfZO9jYqUIgVEdXmXh" +
            "LhXmH8bMsjdtR0c+yM4/QB4SabcFhBAnDpFLqLgNZjEVIVPqBhEb8ASWnGwvsE/h7BxdnuAq2AsXU4q4" +
            "TCjKJLLbzw=")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
    }
}
